### ISSUE TITLE
cdc kafka test container canal-adapter OOM if set resource limit

### ISSUE THREAD

**Issue by purelind** [PingCAP-QE/ci#1893]
### Description
For cdc kafka test case canal_json_adapter_compatibility, we always keep encountering the following error:
check diff timeout
```
table test.binary_columns not exists for 1-th check, retry later
table test.binary_columns not exists for 2-th check, retry later
table test.binary_columns not exists for 3-th check, retry later
table test.binary_columns exists
check diff failed 1-th time, retry later
check diff failed 2-th time, retry later
check diff failed 3-th time, retry later
```
After investigation, it was found that when the resource limit set to `cpu 2, memory 4Gi`, canal-adapter will encounter the following issues.
```shell
2023-03-14 15:23:45.830 [Thread-4] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - Outer adapter sync failed!  Error sync but ACK!
2023-03-14 15:23:46.332 [pool-7-thread-1] DEBUG c.a.o.c.c.adapter.rdb.service.RdbMirrorDbSyncService - DDL: {"data":null,"database":"test","destination":"test","es"
:1678778617779,"groupId":"g1","isDdl":true,"old":null,"pkNames":null,"sql":"ALTER TABLE `test_ddl` ADD INDEX `test_add_index`(`c1`)","table":"test_ddl","ts":1678778
626077,"type":"CINDEX"}
2023-03-14 15:23:46.336 [pool-7-thread-1] ERROR c.a.otter.canal.adapter.launcher.loader.AdapterProcessor - java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdb
c4.MySQLSyntaxErrorException: Table 'test.test_ddl' doesn't exist
java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.test_ddl' doesn't exist
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:171) ~[na:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.batchSync(AdapterProcessor.java:139) ~[client-adapter.launcher-1.1.5.jar:na]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$1(AdapterProcessor.java:97) ~[client-adapter.launcher-1.1.5.jar:na]
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_181]
        at com.alibaba.otter.canal.adapter.launcher.loader.AdapterProcessor.lambda$null$2(AdapterProcessor.java:94) ~[client-adapter.launcher-1.1.5.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.test_ddl' doesn't exist
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.executeDdl(RdbMirrorDbSyncService.java:163) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.rdb.service.RdbMirrorDbSyncService.sync(RdbMirrorDbSyncService.java:73) ~[na:na]
        at com.alibaba.otter.canal.client.adapter.rdb.RdbAdapter.sync(RdbAdapter.java:169) ~[na:na]
        ... 8 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.test_ddl' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_181]
```

### Workaround
Temporarily remove resource limit of container canal-adapter.

**Comment by wuhuizuo** [comment]
fixed. current solved.
